import React from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Sparkles,
  RefreshCw,
  LayoutTemplate,
  Bookmark,
  Image,
  ChevronDown,
} from "lucide-react";
import {
  Draft,
  ContentConfig,
  BrandProfile,
  SavedTemplate,
} from "../_lib/types";
import {
  customerCaption,
  hasFinalImage,
  visibleTemplateCount,
} from "../_lib/utils";
import { VisualTemplateCard } from "./VisualTemplateCard";
import { ScaledTemplatePreview } from "./ScaledTemplatePreview";

interface Props {
  drafts: Draft[];
  setDrafts: (drafts: Draft[]) => void;
  scheduleOneWeekFromTemplates: () => void;
  templateFeedback: string;
  setTemplateFeedback: (val: string) => void;
  generating: boolean;
  refineTemplatesWithFeedback: () => void;
  updatingTemplateIndexes: number[];
  config: ContentConfig | null;
  brandProfile: BrandProfile | null;
  openManualEditor: (draft: Draft, idx: number) => void;
  sendAgentMessage: (msg: string) => void;
  onGenerateVisual: (draftId: string) => void;
  generatingVisualDraftIds: string[];
  imageActionNomi: number;
  onUpdateVisualPrompt: (draftId: string, nextPrompt: string) => void;
  onSaveTemplate: (draft: Draft, index: number) => void;
  onDeleteTemplate: (templateId: string) => void;
  savedTemplates: SavedTemplate[];
}

export function TemplatesTab({
  drafts,
  setDrafts,
  scheduleOneWeekFromTemplates,
  templateFeedback,
  setTemplateFeedback,
  generating,
  refineTemplatesWithFeedback,
  updatingTemplateIndexes,
  config,
  brandProfile,
  openManualEditor,
  sendAgentMessage,
  onGenerateVisual,
  generatingVisualDraftIds,
  imageActionNomi,
  onUpdateVisualPrompt,
  onSaveTemplate,
  onDeleteTemplate,
  savedTemplates,
}: Props) {
  const [confirmDeleteId, setConfirmDeleteId] = React.useState<string | null>(
    null,
  );
  const [confirmGenerateId, setConfirmGenerateId] = React.useState<
    string | null
  >(null);

  if (drafts.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] bg-gray-50/50 rounded-3xl border border-dashed border-gray-200">
        <LayoutTemplate className="w-12 h-12 mb-4 text-gray-300" />
        <h3 className="text-lg font-bold text-gray-900">No Templates Yet</h3>
        <p className="max-w-md mt-1 text-sm text-center text-gray-500">
          Ask the Content Agent to generate templates for you, and they will
          appear here.
        </p>
      </div>
    );
  }

  return (
    <div className="pb-10 space-y-8">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between bg-white p-6 rounded-[24px] border border-gray-100 shadow-sm">
        <div>
          <h2 className="text-2xl font-black tracking-tight text-gray-950">
            Saved Templates
          </h2>
          <p className="mt-1 text-sm text-gray-500">
            Reusable layouts generated by the AI agent.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <Button
            onClick={scheduleOneWeekFromTemplates}
            className="h-10 px-6 font-semibold text-white bg-blue-600 shadow-sm hover:bg-blue-700 rounded-xl"
          >
            Schedule Week
          </Button>
          <Button
            variant="outline"
            onClick={() => setDrafts([])}
            className="h-10 font-semibold text-red-600 transition-colors bg-white border-gray-200 rounded-xl hover:bg-red-50 hover:text-red-700 hover:border-red-100"
          >
            Clear All
          </Button>
        </div>
      </div>

      {/* Template Feedback Bar */}
      <div className="p-6 bg-gradient-to-br from-blue-50 to-indigo-50/30 rounded-[24px] border border-blue-100/50 shadow-sm relative overflow-hidden">
        <div className="absolute top-0 right-0 p-8 pointer-events-none opacity-10">
          <Sparkles className="w-32 h-32 text-blue-600" />
        </div>

        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-blue-600" />
            <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-blue-600">
              AI Studio Refinement
            </span>
          </div>
          <h3 className="mb-1 text-xl font-bold text-gray-900">
            Improve your current templates
          </h3>
          <p className="max-w-xl mb-5 text-sm text-gray-600">
            Give feedback like "remove all logos", "make alignment cleaner", or
            "make them more premium". This updates all active templates below.
          </p>
          <div className="flex flex-col max-w-3xl gap-3 sm:flex-row">
            <Input
              value={templateFeedback}
              onChange={(e) => setTemplateFeedback(e.target.value)}
              onKeyDown={(e) =>
                e.key === "Enter" && refineTemplatesWithFeedback()
              }
              placeholder="Example: make the cards better aligned and premium..."
              className="flex-1 h-12 font-medium text-gray-900 bg-white border-white shadow-sm placeholder:text-gray-400 rounded-xl focus-visible:ring-blue-500/50"
            />
            <Button
              onClick={() => refineTemplatesWithFeedback()}
              disabled={generating || !templateFeedback.trim()}
              className="h-12 px-8 font-bold text-white transition-all bg-blue-600 shadow-sm hover:bg-blue-700 rounded-xl shrink-0 shadow-blue-100"
            >
              {generating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Updating...
                </>
              ) : (
                "Apply Feedback"
              )}
            </Button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">
        {drafts
          .slice(0, visibleTemplateCount(drafts.length))
          .map((draft, idx) => {
            const isSaved = savedTemplates.some(
              (t) => t.id === (draft.templateId || `auto-${draft.id}`),
            );
            const draftHasImage = hasFinalImage(draft);

            return (
              <Card
                key={draft.id}
                className={`rounded-[24px] overflow-hidden transition-all bg-white flex flex-col ${
                  updatingTemplateIndexes.includes(idx)
                    ? "border-blue-400 ring-4 ring-blue-50/50 shadow-md"
                    : "border-gray-100 shadow-[0_2px_10px_-4px_rgba(0,0,0,0.05)] hover:shadow-md"
                }`}
              >
                <CardHeader className="p-5 pb-4 border-b border-gray-50/50 bg-gray-50/30">
                  <div className="flex items-center justify-between">
                    <Badge
                      variant="outline"
                      className="text-[10px] font-bold text-gray-500 border-gray-200 bg-white shadow-sm px-2 py-0.5 rounded-md"
                    >
                      TEMPLATE {idx + 1}
                    </Badge>
                    <div className="flex items-center gap-1.5">
                      {isSaved && (
                        <Badge className="bg-emerald-50 text-emerald-700 hover:bg-emerald-50 text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-md border-none">
                          Library
                        </Badge>
                      )}
                      <Badge
                        className={`${
                          updatingTemplateIndexes.includes(idx)
                            ? "bg-blue-50 text-blue-700"
                            : "bg-gray-100 text-gray-700"
                        } hover:bg-transparent text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-md border-none`}
                      >
                        {updatingTemplateIndexes.includes(idx)
                          ? "Updating..."
                          : "Active"}
                      </Badge>
                    </div>
                  </div>
                  <CardTitle className="mt-4 text-lg font-bold tracking-tight text-gray-900 truncate">
                    {draft.title}
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-5 flex flex-col flex-1 h-full min-h-[480px]">
                  <div className="relative mb-4 group">
                    <ScaledTemplatePreview className="border border-gray-100 shadow-inner bg-gray-50">
                      <VisualTemplateCard
                        draft={draft}
                        index={idx}
                        config={config}
                        brandProfile={brandProfile}
                      />
                    </ScaledTemplatePreview>

                    {updatingTemplateIndexes.includes(idx) && (
                      <div className="absolute inset-0 z-10 flex items-center justify-center transition-all bg-white/80 backdrop-blur-md">
                        <div className="flex flex-col items-center gap-3 p-4 duration-200 bg-white border shadow-xl rounded-2xl border-gray-100/50 animate-in zoom-in-95">
                          <RefreshCw className="w-8 h-8 text-blue-600 animate-spin" />
                          <span className="text-[10px] font-bold text-blue-600 uppercase tracking-widest">
                            Applying AI Edits
                          </span>
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Quick style switcher and actions directly on card */}
                  <div className="flex flex-wrap items-center justify-between gap-2 p-2 mb-4 border border-gray-100 bg-slate-50/80 rounded-xl">
                    <div className="flex items-center gap-1.5">
                      <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                        Style:
                      </span>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button
                            type="button"
                            variant="outline"
                            className="h-7 rounded-lg border border-gray-200 bg-white px-2 text-[11px] font-bold text-gray-700 shadow-sm hover:bg-gray-50 flex items-center gap-1 focus:ring-1 focus:ring-blue-500"
                          >
                            <span>
                              {(() => {
                                const currentStyle = draft.templateIndex ?? idx;
                                if (currentStyle === 0) return "Photo Split";
                                if (currentStyle === 1) return "Graphic Hub";
                                if (currentStyle === 2) return "Dark Loop";
                                if (currentStyle === 3) return "Editorial Band";
                                if (currentStyle === 4) return "Modular Frame";
                                return "Photo Split";
                              })()}
                            </span>
                            <ChevronDown className="w-3 h-3 opacity-60" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent
                          align="start"
                          className="bg-white rounded-xl shadow-lg border border-gray-100 p-1 min-w-[120px] z-50"
                        >
                          <DropdownMenuItem
                            className="text-xs font-semibold text-gray-700 cursor-pointer rounded-lg hover:bg-slate-50 focus:bg-slate-50 px-2 py-1.5"
                            onClick={() => {
                              setDrafts(
                                drafts.map((d) =>
                                  d.id === draft.id
                                    ? { ...d, templateIndex: 0 }
                                    : d,
                                ),
                              );
                            }}
                          >
                            Photo Split
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            className="text-xs font-semibold text-gray-700 cursor-pointer rounded-lg hover:bg-slate-50 focus:bg-slate-50 px-2 py-1.5"
                            onClick={() => {
                              setDrafts(
                                drafts.map((d) =>
                                  d.id === draft.id
                                    ? { ...d, templateIndex: 1 }
                                    : d,
                                ),
                              );
                            }}
                          >
                            Graphic Hub
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            className="text-xs font-semibold text-gray-700 cursor-pointer rounded-lg hover:bg-slate-50 focus:bg-slate-50 px-2 py-1.5"
                            onClick={() => {
                              setDrafts(
                                drafts.map((d) =>
                                  d.id === draft.id
                                    ? { ...d, templateIndex: 2 }
                                    : d,
                                ),
                              );
                            }}
                          >
                            Dark Loop
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            className="text-xs font-semibold text-gray-700 cursor-pointer rounded-lg hover:bg-slate-50 focus:bg-slate-50 px-2 py-1.5"
                            onClick={() => {
                              setDrafts(
                                drafts.map((d) =>
                                  d.id === draft.id
                                    ? { ...d, templateIndex: 3 }
                                    : d,
                                ),
                              );
                            }}
                          >
                            Editorial Band
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            className="text-xs font-semibold text-gray-700 cursor-pointer rounded-lg hover:bg-slate-50 focus:bg-slate-50 px-2 py-1.5"
                            onClick={() => {
                              setDrafts(
                                drafts.map((d) =>
                                  d.id === draft.id
                                    ? { ...d, templateIndex: 4 }
                                    : d,
                                ),
                              );
                            }}
                          >
                            Modular Frame
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </div>

                    <div className="flex gap-1.5">
                      <Button
                        type="button"
                        variant="outline"
                        size="icon"
                        className={`h-7 w-7 rounded-lg shadow-sm ${
                          isSaved
                            ? "bg-emerald-50 text-emerald-700 hover:bg-emerald-100 hover:text-emerald-800 border-emerald-100"
                            : "bg-white text-gray-600 hover:bg-gray-50 border-gray-200"
                        }`}
                        onClick={() => {
                          if (isSaved) {
                            setConfirmDeleteId(
                              draft.templateId || `auto-${draft.id}`,
                            );
                          } else {
                            onSaveTemplate(draft, idx);
                          }
                        }}
                        title={
                          isSaved ? "Remove from Library" : "Save to Library"
                        }
                      >
                        <Bookmark
                          className={`h-3.5 w-3.5 ${isSaved ? "fill-current" : ""}`}
                        />
                      </Button>

                      {!draftHasImage && (
                        <Button
                          type="button"
                          variant="outline"
                          size="icon"
                          className="text-gray-600 bg-white border-gray-200 rounded-lg shadow-sm h-7 w-7 hover:bg-gray-50"
                          disabled={generatingVisualDraftIds.includes(draft.id)}
                          onClick={() => setConfirmGenerateId(draft.id)}
                          title={`Generate AI Image (${imageActionNomi} Nomi's)`}
                        >
                          {generatingVisualDraftIds.includes(draft.id) ? (
                            <RefreshCw className="h-3.5 w-3.5 animate-spin text-blue-600" />
                          ) : (
                            <Image className="h-3.5 w-3.5 text-blue-600" />
                          )}
                        </Button>
                      )}
                    </div>
                  </div>

                  <div className="flex-1 bg-gray-50/50 p-3.5 rounded-2xl border border-gray-100 max-h-[110px] overflow-y-auto custom-scrollbar mb-4">
                    <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1.5 block">
                      Planned Caption
                    </div>
                    <pre className="font-sans text-xs leading-relaxed text-gray-700 whitespace-pre-wrap">
                      {customerCaption(draft.content)}
                    </pre>
                  </div>

                  <div className="grid grid-cols-2 gap-3 mt-auto">
                    <Button
                      onClick={() => openManualEditor(draft, idx)}
                      className="h-10 font-semibold text-white transition-all bg-blue-600 shadow-sm rounded-xl hover:bg-blue-700"
                    >
                      Edit Manually
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() =>
                        sendAgentMessage(
                          `Create stronger variants of this template:\n${draft.content}`,
                        )
                      }
                      className="h-10 font-semibold text-gray-700 transition-all bg-white border-gray-200 shadow-sm rounded-xl hover:bg-gray-50"
                    >
                      AI Variants
                    </Button>
                  </div>
                </CardContent>
              </Card>
            );
          })}
      </div>

      {/* Remove Confirmation Dialog */}
      <Dialog
        open={confirmDeleteId !== null}
        onOpenChange={(open) => !open && setConfirmDeleteId(null)}
      >
        <DialogContent className="max-w-md rounded-[28px] border border-blue-50 bg-white p-6 shadow-xl animate-in zoom-in-95 duration-200">
          <DialogHeader className="text-left">
            <DialogTitle className="text-lg font-black text-gray-950">
              Remove from Library
            </DialogTitle>
            <DialogDescription className="mt-2 text-sm leading-relaxed text-gray-500">
              Are you sure you want to remove this template? It will no longer
              be available in your saved templates library for scheduling.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-3 mt-6">
            <Button
              type="button"
              variant="outline"
              onClick={() => setConfirmDeleteId(null)}
              className="h-10 font-semibold text-gray-700 bg-white border-gray-200 rounded-xl"
            >
              Cancel
            </Button>
            <Button
              type="button"
              onClick={() => {
                if (confirmDeleteId) {
                  onDeleteTemplate(confirmDeleteId);
                  setConfirmDeleteId(null);
                }
              }}
              className="h-10 font-semibold text-white bg-red-600 shadow-sm rounded-xl hover:bg-red-700"
            >
              Remove
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Generate AI Visual Confirmation Dialog */}
      <Dialog
        open={confirmGenerateId !== null}
        onOpenChange={(open) => !open && setConfirmGenerateId(null)}
      >
        <DialogContent className="max-w-md rounded-[28px] border border-blue-50 bg-white p-6 shadow-xl animate-in zoom-in-95 duration-200">
          <DialogHeader className="text-left">
            <DialogTitle className="text-lg font-black text-gray-950">
              Generate AI Visual
            </DialogTitle>
            <DialogDescription className="mt-2 text-sm leading-relaxed text-gray-500">
              Generating a custom AI visual for this template will consume{" "}
              <span className="font-bold text-blue-600">
                {imageActionNomi} Nomi's
              </span>
              . Do you want to proceed?
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-3 mt-6">
            <Button
              type="button"
              variant="outline"
              onClick={() => setConfirmGenerateId(null)}
              className="h-10 font-semibold text-gray-700 bg-white border-gray-200 rounded-xl"
            >
              Cancel
            </Button>
            <Button
              type="button"
              onClick={() => {
                if (confirmGenerateId) {
                  onGenerateVisual(confirmGenerateId);
                  setConfirmGenerateId(null);
                }
              }}
              className="h-10 font-semibold text-white bg-blue-600 shadow-sm rounded-xl hover:bg-blue-700"
            >
              Confirm & Generate
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
