import { db } from '@/lib/db';

const AD_MANAGER_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS ad_products (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, external_product_id TEXT, source TEXT NOT NULL DEFAULT 'manual', title TEXT NOT NULL, handle TEXT, default_url TEXT, image_urls TEXT, metadata TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_personas (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, description TEXT, angle TEXT, targeting_rules TEXT, performance_summary TEXT, status TEXT DEFAULT 'active', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(tenant_id, code))`,
  `CREATE TABLE IF NOT EXISTS ad_hooks (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, persona_id TEXT, angle TEXT, hook_text TEXT NOT NULL, source TEXT DEFAULT 'generated', status TEXT DEFAULT 'active', metadata TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_templates (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL, format_support TEXT, renderer TEXT NOT NULL, design_json TEXT, status TEXT DEFAULT 'active', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_creative_batches (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, product_id TEXT, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', requested_formats TEXT, persona_ids TEXT, hook_ids TEXT, template_ids TEXT, generation_params TEXT, started_at DATETIME, completed_at DATETIME, error TEXT, created_by TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_creatives (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, batch_id TEXT NOT NULL, product_id TEXT, persona_id TEXT, hook_id TEXT, template_id TEXT, format TEXT NOT NULL, media_type TEXT NOT NULL DEFAULT 'image', asset_url TEXT, local_asset_path TEXT, source_asset_refs TEXT, status TEXT NOT NULL DEFAULT 'generated', qc_status TEXT, final_asset_url TEXT, metadata TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_creative_versions (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, creative_id TEXT NOT NULL, version_number INTEGER NOT NULL, action TEXT NOT NULL, asset_url TEXT, local_asset_path TEXT, prompt_or_params TEXT, feedback TEXT, created_by TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_qc_events (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, creative_id TEXT NOT NULL, from_status TEXT, to_status TEXT NOT NULL, reviewer TEXT, feedback TEXT, rejection_reason TEXT, final_asset_url TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_copy_variants (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, creative_id TEXT NOT NULL, variant_index INTEGER NOT NULL, primary_text TEXT NOT NULL, headline TEXT NOT NULL, cta TEXT NOT NULL, policy_status TEXT DEFAULT 'unchecked', policy_notes TEXT, selected INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_destinations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, creative_id TEXT NOT NULL, base_url TEXT NOT NULL, final_url TEXT NOT NULL, utm_source TEXT DEFAULT 'meta', utm_medium TEXT DEFAULT 'paid_social', utm_campaign TEXT, utm_content TEXT, utm_term TEXT, valid INTEGER DEFAULT 0, validation_error TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_campaign_refs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, meta_campaign_id TEXT NOT NULL, name TEXT NOT NULL, objective TEXT, status TEXT, daily_budget_cents INTEGER, metadata TEXT, synced_at DATETIME, UNIQUE(tenant_id, meta_campaign_id))`,
  `CREATE TABLE IF NOT EXISTS ad_adset_refs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, meta_adset_id TEXT, campaign_ref_id TEXT, name TEXT NOT NULL, persona_id TEXT, angle TEXT, budget_cents INTEGER, targeting_json TEXT, placements_json TEXT, status TEXT, metadata TEXT, synced_at DATETIME, UNIQUE(tenant_id, meta_adset_id))`,
  `CREATE TABLE IF NOT EXISTS adset_plans (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, campaign_ref_id TEXT, batch_id TEXT, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', plan_json TEXT NOT NULL, reasoning TEXT, version INTEGER DEFAULT 1, created_by TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_approvals (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, plan_id TEXT, creative_id TEXT, adset_key TEXT, ad_key TEXT, approved_by TEXT NOT NULL, approval_scope TEXT NOT NULL, approved_payload_json TEXT NOT NULL, diff_json TEXT, status TEXT NOT NULL DEFAULT 'approved', created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_publish_jobs (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, plan_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', requested_by TEXT, started_at DATETIME, completed_at DATETIME, error TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_publish_items (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, publish_job_id TEXT NOT NULL, creative_id TEXT, adset_key TEXT, status TEXT NOT NULL DEFAULT 'pending', admanage_asset_id TEXT, admanage_result_json TEXT, meta_campaign_id TEXT, meta_adset_id TEXT, meta_ad_id TEXT, error TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_performance_snapshots (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, date_preset TEXT, spend REAL DEFAULT 0, impressions INTEGER DEFAULT 0, clicks INTEGER DEFAULT 0, ctr REAL DEFAULT 0, cpc REAL DEFAULT 0, cpm REAL DEFAULT 0, lpv INTEGER DEFAULT 0, atc INTEGER DEFAULT 0, ic INTEGER DEFAULT 0, purchases INTEGER DEFAULT 0, cpa REAL DEFAULT 0, roas REAL DEFAULT 0, raw_json TEXT, captured_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_recommendations (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, recommendation_type TEXT NOT NULL, severity TEXT DEFAULT 'info', title TEXT NOT NULL, reasoning TEXT NOT NULL, suggested_action_json TEXT, status TEXT DEFAULT 'open', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, resolved_at DATETIME)`,
  `CREATE TABLE IF NOT EXISTS creative_library_assets (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'image', status TEXT NOT NULL DEFAULT 'ready', source_type TEXT NOT NULL DEFAULT 'url', asset_url TEXT NOT NULL, thumbnail_url TEXT, file_name TEXT, mime_type TEXT, file_size INTEGER, width INTEGER, height INTEGER, duration_seconds REAL, ratio TEXT DEFAULT 'unknown', product_id TEXT, product_name TEXT, product_url TEXT, persona_id TEXT, persona_name TEXT, campaign_id TEXT, tags TEXT, notes TEXT, copy_hint TEXT, landing_page_url TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ad_audit_log (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, actor TEXT, action TEXT NOT NULL, entity_type TEXT, entity_id TEXT, before_json TEXT, after_json TEXT, reason TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`,
];

let adManagerInitialized = false;

export async function initAdManagerDb() {
  if (adManagerInitialized) return;
  for (const sql of AD_MANAGER_SCHEMA) {
    await db.execute(sql);
  }
  adManagerInitialized = true;
}
